### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by vctibor** [vctibor/Zuma#4]
### Fixes
- [ ] Fix scopes: constants declared multiple times in different scopes have unexpected values
- [ ] Fix text rendering using resvg

### Features
- [ ] Boolean data type
- [ ] Relational, logical and arithmetic operators + - * / > < = & |  ! and parentheses.
- [ ] if and for
- [ ] remaining basic geometric elements: ellipse, polygon
- [ ] paths
- [ ] transformations: rotate, scale, translate
- [ ] user defined functions
